export { default as Dashboard } from './Dashboard'
export { default as Categories } from './Categories'
export { default as Tests } from './Tests'
export { default as TestEditor } from './TestEditor'
export { default as Users } from './Users'
export { default as Analytics } from './Analytics'
export { default as Settings } from './Settings'
export { default as Login } from './Login'
